# @package _global_
hydra:
  run:
    dir: outputs/opt:${exp_name}/${now:%Y-%m-%d_%H-%M-%S}

exp_name: iPCRNet_modelnet_
dataset_path: data/modelnet40_ply_hdf5_2048
eval: false

data: 
  dataset_type: modelnet
  num_points: 1024

pointnet:
  pointnet: tune
  emb_dims: 1024
  symfn: max
  
training:
  seed: 1234
  workers: 4
  batch_size: 32
  epochs: 500
  start_epoch: 0
  optimizer: Adam
  resume: null
  pretrained: null
  cuda: 0
