# @package _global_

exp_name: iPCRNet_dude_cd
dataset_path: data/dude
eval: false

data: 
  dataset_type: dude
  num_points: 1024
  registration_data:
    angle_range: 45
    translation_range: 1

pointnet:
  pointnet: tune
  emb_dims: 1024
  symfn: max

ipcrnet:
  max_iteration: 8

training:
  seed: 1234
  workers: 4
  batch_size: 32
  epochs: 500
  start_epoch: 0
  optimizer: Adam
  resume: null
  pretrained: outputs/iPCRNet_modelnet_emdloss_epoch500/models/best_model.t7
  cuda: 0
  loss: cd