# @package _global_

exp_name: iPCRNet_cd
dataset_path: data/modelnet40_ply_hdf5_2048
eval: false

data: 
  dataset_type: modelnet
  num_points: 1024
  registration_data:
    angle_range: 45
    translation_range: 1

pointnet:
  pointnet: tune
  emb_dims: 1024
  symfn: max

ipcrnet:
  max_iteration: 8

training:
  seed: 1234
  workers: 4
  batch_size: 32
  epochs: 500
  start_epoch: 0
  optimizer: Adam
  resume: null
  pretrained: null
  cuda: 0
  loss: cd